name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libtbb-dev
    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build
    - name: Run C++ tests
      run: ./build/test_overlap
    - name: Install python deps
      run: pip install pytest ezdxf reportlab matplotlib PyPDF2
    - name: Run Python tests
      run: pytest -v
