name: Nesting CLI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build with MSBuild
      run: msbuild nesting-master/Nesting.sln /p:Configuration=Release

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: Nesting-windows
        path: |
          nesting-master/x64/Release/*.exe
